# -*- coding: utf-8 -*-
"""Python basic programs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1POqBjPvPqHP6bpL0u5rXA5oppf06z-8c

#Adding two numbers:
"""

a = 10
b = 20
c = a + b
print(c)

"""#Maximum of three numbers:"""

a = 10
b = 20
c = 30
if a>b and a>c:
    print("Maximum number is a:",a)
elif b>c:
    print("Maximum number is b:",b)
else:
    print("Maximum number is c:",c)

"""#Factorial of a number:"""

def fact(n):
    if n==1 or n==0:
        return 1
    elif n<0:
        return "Does not exist"
    else:
        return n*fact(n-1)
n = 4
print(fact(4))